### ISSUE TITLE
Crash on entering config in modmenu

### ISSUE THREAD

**Issue by Sarelth** [JackFred2/ChestTracker#10]
**To Reproduce**
Attempted to open the mod config in-game. Immediately crashed to desktop, attempted again and it repeated. 

**Crash Report**
[crash-2020-10-08_00.27.26-client.txt](https://github.com/JackFred2/ChestTracker/files/5345745/crash-2020-10-08_00.27.26-client.txt)

**Additional context**
I added a few extra fabric mods today, so it could be related to one of them, not sure.

**Comment by JackFred2** [comment]
[Looks to be an issue with TooltipFix and AutoConfig](https://github.com/kyrptonaught/tooltipfix/issues/1); it's a new mod so it'll most likely be fixed soon.
