### ISSUE TITLE
Show GUI preview of shulker box

### ISSUE THREAD

**Issue by MrFums** [JackFred2/ChestTracker#103]
**Describe the solution you'd like**
Show a GUI preview of what is in the shulker box (see image for what I mean) 
![image](https://github.com/JackFred2/ChestTracker/assets/57535680/762cd480-9213-4195-9727-81dbe4a68856)

**Describe alternatives you've considered**
Using modules / mods that add this to the game when hovering over a shulker in an actual container works but for some reason doesn't work with the mod.

**Additional context**
Either support for which or a workaround mod that adds this functionality to the game.

**Comment by JackFred2** [comment]
What mods are you using for the tooltip? Assuming you're on 1.19.4 anyway, [Shulker Box Tooltip](https://modrinth.com/mod/shulkerboxtooltip) works for me:
![image](https://github.com/JackFred2/ChestTracker/assets/8350692/35145f65-beeb-4c10-9047-e3f041bbfd5d)

**Comment by MrFums** [comment]
Ahh perfect, thanks that mod works. I tried both Tweakeroo's built in preview aswell as my hacked clients shulker preview module to no avail. Shulker Tooltips works fine. Thank you!
