### ISSUE TITLE
keyboard crash

### ISSUE THREAD

**Issue by some-du6e** [JackFred2/ChestTracker#104]
https://pastebin.com/abXjJGcJ
edit: made it a pastebin bc it looks horrible

**Comment by JackFred2** [comment]
Could you post the full crash report so I can see the mod list and versions?

**Comment by XerwinXpl2** [comment]
duplicate of mine from what i see #64 same error (mine was caused by typing before gui is loaded first time)

**Comment by some-du6e** [comment]
#64 describes this pretty well
