### ISSUE TITLE
Can no longer forget chests in 2.x versions

### ISSUE THREAD

**Issue by Xaver106** [JackFred2/ChestTracker#106]
In the 1.x version, every chest had a little icon which enabled you to change settings specific to the chest. I miss this option on the latest 2.x version. Did I miss something?
Tested with:
- Minecraft 1.20.2
- Fabric Loader 0.14.24
- Fabric API 0.90.4
- Mod Menu 8
- WhereIsIt 2.2.4
- YetAnotherConfigLib 3.3.0
- Chest Tracker 2.0.3

**Comment by JackFred2** [comment]
Currently that button isn't in the rewrite; I'd originally added it as the main way to open the GUI but I personally ended up using the hotkey primarily so it wasn't a priority. I plan on adding it back once i figure out a nice solution to placing it on GUIs without it overlapping with other mods' screen elements / addons (such as InvTweaks).

**Comment by Xaver106** [comment]
Opening the GUI is not my issue. Forgetting Chests or manually adding chests to the memory is my issue. I usually never automatically saved chests, only added my own chests manually. I didn't find an option for that.
My suggestion would be: When opening the GUI from a container, add some options to manage this container. Also, please reintroduce the option to only manually save containers.

**Comment by Xaver106** [comment]
@JackFred2 I can't make the mod to forget anything. Was the forget options removed in 2.x?

**Comment by JackFred2** [comment]
I'll add a manual management tab in the memory bank settings screen (delete outside / inside a range, delete all) in next release; the small Chest Tracker widget for individual chests is planned but will have wait a bit

**Comment by JackFred2** [comment]
2.0.4+1.20.2 for forget panel; button will come in future
