### ISSUE TITLE
Chest Tracker enhancements

### ISSUE THREAD

**Issue by sternschnaube** [JackFred2/ChestTracker#107]
I would like to have a button from the player inventory to the Chest Tracker gui, and from there a button back to the player inventory.
Position control per config for the buttom of the player inventory would be cool.

Some high numbers overlapping, could you downscale them please?

![image](https://github.com/JackFred2/ChestTracker/assets/120551916/0f520a59-ec11-4e4d-8014-b4748878d2a1)

**Comment by JackFred2** [comment]
Added a text GUI scale modifier in the settings under GUI in 9e72dbbee85b052710a400c74e8dff52d94e4774, release 2.0.6

Bringing the inventory button back is a future plan as I want to prototype a decent system for positioning it first.

**Comment by sternschnaube** [comment]
Thanks, great to hear 😊
