### ISSUE TITLE
ShareEnderChest compatibility

### ISSUE THREAD

**Issue by sternschnaube** [JackFred2/ChestTracker#108]
https://modrinth.com/mod/share-ender-chest

It adds his own inventory. Could you add a own button, like enchanted ender chest as icon, for this inventory please?
Chest Tracker shows now the last opened inventory. Own ender chest or from ShareEnderChest.

![image](https://github.com/JackFred2/ChestTracker/assets/120551916/7f47a6b7-6f56-44c9-8965-464cae1ae10f)

Do you plan some more sorting methods, like just inventories like hoppers, chests and dimension based?

**Comment by JackFred2** [comment]
Added in e9128ceea30618cecdb1d8865554034277ca9c53, release 2.0.6.

Not sure what you mean by the second part; do you simply mean more filtering options such as common + hoppers, or do you mean different filtering based on the dimension?

**Comment by sternschnaube** [comment]
Thanks, fast!!!

I mean, to display buttons on the left as example, to show all content just from Hoppers, or Chests. But not merged and counted together.

Like: overworld:hoppers, nether:chests

Even dimension support.

**Comment by sternschnaube** [comment]
Thanks, fast!!!

I mean to display buttons on the left as example, to show all content just from Hoppers, or Chests. But not merged and counted together.
