### ISSUE TITLE
Dream Dimension compatibility

### ISSUE THREAD

**Issue by sternschnaube** [JackFred2/ChestTracker#109]
It would be great to support this specific sleep dimension. 

https://legacy.curseforge.com/minecraft/mc-mods/thepeebrain-dream-dimension

**Comment by JackFred2** [comment]
Should just work; though I'm not planning on working on the legacy version anymore it does appear to notice that dimension, sans a specific icon:
![image](https://github.com/JackFred2/ChestTracker/assets/8350692/4970e4f3-2803-499d-9e49-5b879e79ebd4)

**Comment by sternschnaube** [comment]
Thanks for letting me know.

Could you explain please what you mean with "legacy version"? Thanks 😊

**Comment by JackFred2** [comment]
Legacy versions built on the old codebase (`legacy-1.x` branch), currently for Minecraft 1.20.1 and below.
