### ISSUE TITLE
Minor annoyance in minecraft log

### ISSUE THREAD

**Issue by yuuki-san** [JackFred2/ChestTracker#11]
**Describe the bug**
...
[main/WARN]: Error loading class: grondag/canvas/render/CanvasWorldRenderer (java.lang.ClassNotFoundException: grondag/canvas/render/CanvasWorldRenderer)
[10:33:41] [main/WARN]: @Mixin target grondag.canvas.render.CanvasWorldRenderer was not found chesttracker.mixins.json:MixinCanvasWorldRenderer
...

**To Reproduce**
Use the mod

**Expected Result**
...
[xx:xx:xx] [main/WARN] CanvasWorldRenderer not found - disabling feature

**Comment by JackFred2** [comment]
Added a mixin plugin to remove the warning.
