### ISSUE TITLE
[1.20.3] Mod crashes the game when try to open GUI.

### ISSUE THREAD

**Issue by dobisan** [JackFred2/ChestTracker#110]
With the [1.20.3] Chest Tracker 2.1.1+1.20.3 beta version the mod crashes the game when I try to open the mod GUI.

Minecraft provides the following error code and description.

_The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: com/blamejared/searchables/api/autcomplete/AutoCompletingEditBox_

**Comment by JackFred2** [comment]
Currently searchables doesn't have a 1.20.3/4 version out; that's why I haven't marked it as 1.20.3 proper. If you do want to use it, you'll need to add a dependency override as seen in the latest GitHub release's notes: https://github.com/JackFred2/ChestTracker/releases/tag/v2.1.1%2B1.20.3
