### ISSUE TITLE
Bad Russian translation 

### ISSUE THREAD

**Issue by murolem** [JackFred2/ChestTracker#113]
Russian translation is pretty bad.

Is there any way I can contribute to make the translation better?

**Comment by JackFred2** [comment]
Assuming you're talking about the legacy 1.x version: sure. You can fork the repository, and update the [`src/main/resources/assets/chesttracker/lang/ru_ru.json`](https://github.com/JackFred2/ChestTracker/blob/a736c84343b3cd94a47bed510d2c6d1187346bb9/src/main/resources/assets/chesttracker/lang/ru_ru.json) file in the `legacy-1.x` branch which contains the Russian translation; the English translations are in [`en_us.json`](https://github.com/JackFred2/ChestTracker/blob/a736c84343b3cd94a47bed510d2c6d1187346bb9/src/main/resources/assets/chesttracker/lang/en_us.json). Once you're done, submit a pull request and I'll push a new release. If you're not comfortable with making a PR, feel free to just upload the updated `ru_ru.json` file on this issue and I'll add it.

**Comment by murolem** [comment]
PR in https://github.com/JackFred2/ChestTracker/pull/114
