### ISSUE TITLE
game crash 

### ISSUE THREAD

**Issue by AlexGhica101** [JackFred2/ChestTracker#116]
for 1.20.4 it keeps crashing when i try to start the game:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'whereisit'!  Exit code:-1

how do i fix it?

**Comment by JackFred2** [comment]
can you post the full crash report? should be under `crash-reports` in your game directory

**Comment by AlexGhica101** [comment]
[crash-2024-01-07_10.42.15-client.txt](https://github.com/JackFred2/ChestTracker/files/13919578/crash-2024-01-07_10.42.15-client.txt)

**Comment by JackFred2** [comment]
Update YACL, you have the 1.20.2 version installed: https://modrinth.com/mod/yacl/version/3.3.1+1.20.4-fabric
