### ISSUE TITLE
Chests aren't being tracked on hypixel

### ISSUE THREAD

**Issue by NotSoNitro** [JackFred2/ChestTracker#117]
Tryna use this on my Hypixel SMP but the tracker just doesn't track anything or log any of the items.

**Comment by minhperry** [comment]
Can confirm, Hypixel SMP 1.20.2

**Comment by JackFred2** [comment]
can have a look later; hypixel has some special handling for skyblock so currently SMP is ignoredOn 13 Jan 2024 01:30, Phan Minh ***@***.***> wrote:
Can confirm, Hypixel SMP 1.20.2

**Comment by JackFred2** [comment]
Added support for SMP. It should work the same as a regular server, with a couple caveats:
- Currently doesn't differentiate between SMP servers; Chest Tracker has a profile feature for this
- It has to read the chat to determine when it joins an SMP, so make sure your chat settings isn't 'Fully Hidden'.
![image](https://github.com/JackFred2/ChestTracker/assets/8350692/e5ed4116-2dc7-4752-a4a4-6f5e4707d504)

If any issues do pop up, feel free to reopen this issue.
