### ISSUE TITLE
Search Button in GUI not there

### ISSUE THREAD

**Issue by bruh1273** [JackFred2/ChestTracker#118]
In the older versions of chest tracker, there was a little magnifying glass button in the top right of all handled screens that would open the chest tracker GUI. I cannot find the config option for it, or it was downright removed all together. Nonetheless, I would like to see the feature re-added, or to be shown where to enable the feature, as this was my main way to open the GUI.

**Comment by JackFred2** [comment]
Being worked on, just taking time to make it work with some other requested features such as client-side renaming.

https://i.imgur.com/qq9e1UY.gifv

**Comment by JackFred2** [comment]
2.2.0, skipped the extra features for now
