### ISSUE TITLE
How do you name chests?

### ISSUE THREAD

**Issue by TheFlagen430297** [JackFred2/ChestTracker#124]
I have read the wiki and found [where it talked about how to handle named chests](https://github.com/JackFred2/ChestTracker/wiki/Memory-Bank-Settings#only-named), however, I can't find where or how you name it.
If I have the **Only Named: ON** the items don't get added to the list, I have named the chest via the anvil but with no luck.
So how do you apply a name to a chest?

**Comment by JackFred2** [comment]
I'm struggling to reproduce this but it sounds like a bug. Chest Tracker (currently) doesn't do the renaming, it just reads from the GUI title. What I can think of:

1. Are you using a modded chest or container? might have a custom GUI implementation that Chest Tracker isn't reading.
2. Make sure that other settings aren't blocking the chest (filtered out with 'Common Containers')

![can't reproduce](https://github.com/JackFred2/ChestTracker/assets/8350692/24607992-3555-433e-8815-6c285ed2687e)

**Comment by TheFlagen430297** [comment]
The chest is on a Paper Server.
And I changed the settings to what you had it on.

This is odd, I logged out of the server that I was playing and just now logged back in to test further, and now any chest that I open thinks it's named even when it was not named
![image](https://github.com/JackFred2/ChestTracker/assets/60035052/72b610ec-cdae-4505-8d4e-101fe5ac2ea9)
The *Testing* is the edited name. The other 2 are normal.

Also, I deleted and replaced the original Memory Bank.
However, the name-only settings were on the 2nd *(Current)* Memory Bank.
*(I was playing around with the settings)*

**Comment by JackFred2** [comment]
Still not sure about the original issue, but I've added the ability to rename stuff client-side.
![wbLYaKvhwk](https://github.com/JackFred2/ChestTracker/assets/8350692/25cb9aec-ac0b-44f8-8ca0-0522df3cc186)

Hopefully the underlying issue you had is solved by the internal changes between then and now.
