### ISSUE TITLE
Visual glitch

### ISSUE THREAD

**Issue by Flus1234** [JackFred2/ChestTracker#127]
There is a visual glitch when I open any chest for the first time. If I understand correctly, there should be a name above the chest, but this appears instead. In the settings, I can only reduce the size, but not disable it in any way.
![2024-02-04_20 55 18](https://github.com/JackFred2/ChestTracker/assets/61036027/2ea43e4d-f730-4af7-9c94-e70c4fcb2877)
![2024-02-04_21 00 24](https://github.com/JackFred2/ChestTracker/assets/61036027/eb336417-0690-415b-8b62-4f9f134bc922)

**Comment by JackFred2** [comment]
Looks like a fairly bad mod conflict; can you upload your mod list? (a full `latest.log` file will do)

**Comment by Flus1234** [comment]
[latest.log](https://github.com/JackFred2/ChestTracker/files/14159571/latest.log)

**Comment by Flus1234** [comment]
This glitch occurs only on the Origin Realms server (they have a mandatory resource pack). I went to another server, checked in a single game - there is no such thing.

**Comment by JackFred2** [comment]
Fixed in 2.3.0
