### ISSUE TITLE
Forget Container

### ISSUE THREAD

**Issue by SirPotato42** [JackFred2/ChestTracker#128]
In older versions of the mod, holding shift in a container would change the magnifying glass icon to a + or x depending on whether or not the chest was stored in memory, and pressing the button while holding shift would respectively add it to the memory or forget it.

There was also a very convenient feature in the settings; a toggle to automatically remember chests or not.

I would like to see these features re-added to the latest version of the mod.

**Comment by JackFred2** [comment]
Added as part of 2.4; it works by allowing you to block a chest or container from being tracked. Additionally can work in the opposite direction as an allow-list system.
![PSsVExqpML](https://github.com/JackFred2/ChestTracker/assets/8350692/c95ed660-94ce-45e0-ad4f-9c05c163cb1c)
