### ISSUE TITLE
Option to not show chest names in world

### ISSUE THREAD

**Issue by RuiNtD** [JackFred2/ChestTracker#129]
The server [Origin Realms] uses a resource pack and custom names on all containers. However, this creates a very annoying billboard GUI on all chests. There should be an option, both globally and per-server, to not show chests names in the world.
![image](https://github.com/JackFred2/ChestTracker/assets/1149870/93d8f123-176d-45df-8f50-c999b00b8eab)

[Origin Realms]: https://originrealms.com/

**Comment by JackFred2** [comment]
Added a per-memory-bank setting to disable names for 2.3.0

**Comment by spocane** [comment]
Can you add this to the main settings file, this was really hidden and was a pain to figure out how to disable showing the named chests, plus with it as is, you have to individually toggle this setting for each world.
