### ISSUE TITLE
Causes OpenGL errors when playing with shaders.

### ISSUE THREAD

**Issue by FeistyKit** [JackFred2/ChestTracker#13]
When I try to load shaders using optifabric without the mod, the shaders work fine, but when I try to use it with the mod, this happens: https://imgur.com/a/JmhKjlZ 

All I needed to reproduce it was to try and load shaders with optifabric, optifine and chesttracker loaded. I'm running 1.16.3

What I thought would happen is the shaders working correctly but it's giving those weird symbols.

Also yes I am going by the github format lol. I would really love if you updated this, as this mod is one of my most favorite ones ever!

**Comment by JackFred2** [comment]
Cheers for the report; I'm working on it. It's something to do with the text rendering code and hand rendering code (you can see shaders working when you disable the HUD).

**Comment by JackFred2** [comment]
Got an idea for this

**Comment by JackFred2** [comment]
Fixed in 96445a43e80e13399c112e0d6654c16fb404658f
