### ISSUE TITLE
Custom handling for Origin Realms

### ISSUE THREAD

**Issue by RuiNtD** [JackFred2/ChestTracker#130]
The server [Origin Realms] uses a resource pack and custom names on all containers to allow for custom GUIs (even though they look the same as vanilla?). This causes a few issues with Chest Tracker:
1. Chest data is always preserved. This *can* be disabled from the memory bank settings, but Origin Realms does still allow custom names on containers. 
2. All chests show their names in world, causing an annoying billboard GUI on all chests. 

![image](https://github.com/JackFred2/ChestTracker/assets/1149870/10fca4ba-1c47-420c-ad63-c2c650d4126f)

It would be nice if Chest Tracker could handle Origin Realms' containers. As far as I can tell, OR uses several 0 width characters before the name of the chest, then explicitly adds in the name of the container (whether renamed or default) at the end. This also happens with hoppers, furnaces, and shulker boxes; which don't even use a custom texture, but still has two invisible characters (no idea why) before their names. A potential solution could be to parse out all non-ASCII characters, then use a black list to detect default container names (Chest, Large Chest, Barrel, Item Hopper, Shulker Box, Furnace, Smoker, Blast Furnace)

[Origin Realms]: https://originrealms.com/

**Comment by JackFred2** [comment]
Had a look at the resource pack; it replaces certain characters (for example, Korean letters - try typing `쇌` in chat) in the default font with the full container top-half textures. I'll add some filtering as an off-by-default option for custom names, though it won't be just ASCII to try and maintain as much language support as possible.

Mentioning #127 as a reminder

**Comment by JackFred2** [comment]
Fixed in 2.3.0; it won't display non-renamed chests now. There's also filtering options if you have renamed something in an anvil.
