### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by aMazeInRunar** [JackFred2/ChestTracker#138]
Hi, I've been using the legacy version of this mod since it dropped, and last year I updated my world to 1.20.1 since it had the most mods available at the time. I've recently started learning Java, just so I could compile some mods that didnt have 1.20.1. I just wanted to ask if that's possible with this mod, and if it would be difficult. I dont really know what I'm doing, but trying can't hurt.
Thanks for the mod anyway, I can't live without it =)

**Comment by JackFred2** [comment]
[Chest Tracker does have a legacy 1.20.1 build.](https://modrinth.com/mod/chest-tracker/version/1.1.23)

If you do want to tinker yourself; just clone the Git repo and checkout `legacy`. 

The only issue I think you may have is that Where Is It legacy versions are hosted on GitHub packages which require auth; you can either [authenticate](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#authenticating-to-github-packages), or clone [Where Is It's legacy branch](https://github.com/JackFred2/WhereIsIt/tree/legacy) and publish to `mavenLocal` beforehand.

**Comment by aMazeInRunar** [comment]
Excuse me for the misunderstanding, I meant that I'm already using the legacy version of 1.20.1. I was wondering if it's possible to make a 1.20.1 version of the newer updates of Chest Tracker.

**Comment by JackFred2** [comment]
Should be possible; the main things are making sure you depend on the correct versions of deps (Where Is It, Searchables, YACL) and that there were quite a few GUI-related changes (stuff like moving into a sprite system).
