### ISSUE TITLE
in chest gui item mark

### ISSUE THREAD

**Issue by Godwhitelight** [JackFred2/ChestTracker#15]
**Describe the solution you'd like**
What would you like to see in the mod?
ween you are clicking the item and opening the chest it will mark the item with a colored squre on the item
**Describe alternatives you've considered**
you can do a raw - column text message that saying were is the item

**Additional context**
![test](https://user-images.githubusercontent.com/73111474/108604719-4bee0980-73b8-11eb-8dc7-b643ae3a31dc.png)

**Comment by JackFred2** [comment]
![image](https://user-images.githubusercontent.com/8350692/108766643-51c92380-754d-11eb-9ad9-5eb8495e65b8.png)
Added
