### ISSUE TITLE
1.20.4 fabirc can cause button Y is bind but connot modify

### ISSUE THREAD

**Issue by SheepXiu** [JackFred2/ChestTracker#158]

**Comment by JackFred2** [comment]
I'm not sure I understand the issue, but the search button (default Y) is under 'Where Is It' in the keybinds menu (since CT is technically an extension).

**Comment by SheepXiu** [comment]
Sorry maybe I didn't use the right expressions. I'll try my best.

My problem is that after installing the ChestTracker module, pressing Y will say "This is not a container, cannot sync" or "Unsync" above the inventory GUI (depending on which box the cursor is pointing at).

I actually download both  'Where Is It' and 'ChestTracker', but I can be basically sure that ‘ChestTracker’ causes the problem because I've tried repeatedly installing mods to locate this key binding issue.

Maybe the following photo can describe my question.
![image](https://github.com/JackFred2/ChestTracker/assets/144374420/bae917e2-424e-4b06-8fa5-c98812e0e8d1)
![image](https://github.com/JackFred2/ChestTracker/assets/144374420/b9709ba8-f6b1-4761-b729-cdfad6bee7d5)

---

_but the search button (default Y) is under 'Where Is It' in the keybinds menu (since CT is technically an extension)._

That is the question.

I changed the 'Where Is It' button binding in Minecraft keybind Setting, but it still had the problem I mentioned.

**Comment by JackFred2** [comment]
Turns out this isn't a Chest Tracker feature; [it's a part of the Litematica Printer fork](https://github.com/zhaixianyu/litematica-printer/blob/a2aaeb81b60686324bc85506c96dc15362bb809c/src/main/java/me/aleksilassila/litematica/printer/printer/zxy/Utils/ZxyUtils.java#L131). You may be able to change the keybindings for that.

**Comment by SheepXiu** [comment]
It actually works. Tks very much.

If litematica printer is not installed on the server, some functions of litematica printer on the client will not be displayed, such as the "container sync" encountered above. 

Maybe the ChestTracker let client litematica printer to think the server has also installed the litematica printer.  >-：

But the problem is solved, tks again~  <-:

**Comment by JackFred2** [comment]
Seems to be some issue in that printer fork yeah. First party integration might be an idea of Chest Tracker in the future.

Glad it's solved.
