### ISSUE TITLE
Cant see outlines from chests that are too far away

### ISSUE THREAD

**Issue by shouxd** [JackFred2/ChestTracker#16]
Hi, I just updated chesttracker from version 0.7.11 and I can no more see outlines from far away. I could perfectly see distant outline boxes in the horizon if the chest I was looking for was really distant, like 10.000 blocks away or so, but no more with latest version

**Comment by JackFred2** [comment]
Fixed in JackFred2/WhereIsIt@f429850d601aee1c5f9fcab83a5f8372ed7949f7

**Comment by JackFred2** [comment]
Pushed 0.8.2 on curse with the fix
