### ISSUE TITLE
Feature Request: Enter key Focuses Search Bar / Toggle Suggestions

### ISSUE THREAD

**Issue by Gymcap** [JackFred2/ChestTracker#160]
1.20.1 Fabric

This is just a simple feature request to make the chest tracker search bar focus with the Enter key.

Expected usage:
Open Chest Tracker GUI
Press Enter (search bar gets focused)
Type your item

My reason for wanting this is that currently when searching for an item, I must remove my hands from the keyboard in order to manually click the search bar, and I would find it much more convenient to simply tap enter.

---------

Another option could be to have the search suggestions toggle between hidden and shown when pressing tab, with an option to show or hide by default. This would make the "auto focus search bar" more viable since the suggestions wouldnt be covering the items unless you intentionally are looking for suggestions.

----------

Truthfully either of these changes, or something similar, would be amazing.

**Comment by Gymcap** [comment]
Directly after making this, i noticed that opening the Chest Tracker GUI and pressing 'tab' 3 times results in the search bar getting focused. Another great option instead of the ones above could be to simply find a way to lower this to a single tab press to focus/unfocus the search bar.

**Comment by JackFred2** [comment]
Done for 2.4.2; the search bar is now the first thing to get focused when you press tab
