### ISSUE TITLE
Floating point precision error

### ISSUE THREAD

**Issue by gargamelius** [JackFred2/ChestTracker#161]
Pls fix the weird renders when you go far out <3 

https://github.com/JackFred2/ChestTracker/assets/76599695/7857e817-0e16-4e3d-8b4c-b17396b69cf5

**Comment by JackFred2** [comment]
fixed in https://github.com/JackFred2/WhereIsIt/commit/b8d5b74eaada7d439e0bfb01b5ed68020419eaae
