### ISSUE TITLE
Turn off name

### ISSUE THREAD

**Issue by pixo2000** [JackFred2/ChestTracker#167]
Hi, i cannot find the option to turn off the names. where exactly can i find it?

**Comment by JackFred2** [comment]
Assuming you're on 2.x, under Memory Bank Settings > Compatibility there's a 'Display Container Names' setting.
![javaw_lDfwYdTLsm](https://github.com/JackFred2/ChestTracker/assets/8350692/822c3a1a-95b1-44d0-962d-ea1f7a449d80)

**Comment by pixo2000** [comment]
funny. im on 2.x 1.20.2 but cannot find it
![grafik](https://github.com/JackFred2/ChestTracker/assets/91846430/1e354678-ffff-40ef-9120-2c6486ec20f3)

**Comment by pixo2000** [comment]
![grafik](https://github.com/JackFred2/ChestTracker/assets/91846430/c6cd187e-c8a2-41ab-b0d0-d8cdde0208bb)
The newer 1.20.2 versions are just crashing. could be because its an older fabric api version idk

**Comment by JackFred2** [comment]
Yeah that's [wildly outdated](https://modrinth.com/mod/chest-tracker/version/2.4.3+1.20.2); what's the crash report with the newer versions?

**Comment by JackFred2** [comment]
These versions with no other mods are working for me on 1.20.2, Fabric Loader 0.15.11, Java 17
![image](https://github.com/JackFred2/ChestTracker/assets/8350692/6f0a8141-dac3-498b-bec9-1a2a10f3d5ff)

**Comment by JackFred2** [comment]
Assuming resolved
