### ISSUE TITLE
Inventory Profiles Next compatibility

### ISSUE THREAD

**Issue by Velaron** [JackFred2/ChestTracker#169]
Can a compatibility option be added so buttons don't overlap? Can't seem to find an option as https://github.com/JackFred2/ChestTracker/issues/2 suggests
![image](https://github.com/JackFred2/ChestTracker/assets/53096779/0bdeaf18-7ac0-4e3d-b2ad-4bc97354b285)

**Comment by JackFred2** [comment]
If you're on 2.x, you can click and drag the button off the menu.

If you're on the legacy 1.x versions, you'll have to tinker around with the old [datapack system](https://github.com/JackFred2/ChestTracker/tree/legacy-1.x?tab=readme-ov-file#button-positions). Sorry, I know it isn't great. 2.x is available for 1.20.1 on the [GitHub releases](https://github.com/JackFred2/ChestTracker/releases/tag/v2.4.3%2B1.20.1), but you'll have to add the memory bank data again.

**Comment by Velaron** [comment]
Thank you, didn't know the button is moveable
