### ISSUE TITLE
Game Crash on Placing Shulker box

### ISSUE THREAD

**Issue by SaiCode-DEV** [JackFred2/ChestTracker#171]
Link to Crashlog:

https://mclo.gs/4PV19op

MC 1.21, Fabric, Chest Tracker 2.4.7+1.21

**Comment by JackFred2** [comment]
Can't reproduce so will have a further look later, but for whatever reason Apache Comons Lang3 3.14.0 seems to not be loading right even though it shows in the libraries at the top.

Related to #168

**Comment by SaiCode-DEV** [comment]
I saw the #168 but sadly cant turn it off to check. 
Opening exiting placed Shulkers is perfectly fine, just the on place scan is crashing the game.

**Comment by ReaperGhost187** [comment]
im having the same issue as above.

**Comment by JackFred2** [comment]
I'll rejig it to not use that library; annoying because it doesn't 'solve' it but I can't figure out why the method/class isn't loading. Let me know if it crops up again.
