### ISSUE TITLE
I'm sorry, but could you help me?

### ISSUE THREAD

**Issue by ffddf111** [JackFred2/ChestTracker#187]
Excuse me, but how do I make the contents of an ender chest visible using the shulkerbox tooltip?

**Comment by JackFred2** [comment]
Looks like the integration was broken at some point and I didn't notice, give a minute

**Comment by JackFred2** [comment]
yeah found the issue, will push it out now

**Comment by ffddf111** [comment]
> 결국 발견했어요. 지금 푸시할게요.

I'm trying it now and it doesn't work?
Or maybe I did it wrong?
Or do I have to close and restart the server?

**Comment by JackFred2** [comment]
Sorry, I meant it was an issue in my code. I'm releasing a new version now that will fix it, you'll need to update to 2.4.12.

**Comment by ffddf111** [comment]
> Sorry, I meant it was an issue in my code. I'm releasing a new version now that will fix it, you'll need to update to 2.4.12.

Thank you
