### ISSUE TITLE
Next/Previous page buttons cannot be retextured.

### ISSUE THREAD

**Issue by CodeF53** [JackFred2/ChestTracker#19]
![image](https://user-images.githubusercontent.com/37855219/112740645-beb04e80-8f3b-11eb-8dcb-283b81e930ac.png)
The Next Page / Previous page button backgrounds cannot be retextured, leading to an ugly look when using dark themed texture packs.

**Comment by JackFred2** [comment]
Should be good to go in 0.8.10, there's textures for disabled, hovered and normal versions now. Also, if you show libraries in ModMenu, you can enable dark mode in LibGui's config which brightens the main window's text.
