### ISSUE TITLE
Modrinth update

### ISSUE THREAD

**Issue by KIRUYXAN** [JackFred2/ChestTracker#193]
Why on modrinth the latest version of the mod for 1.20.1 is 1.1.23

**Comment by JackFred2** [comment]
Mainly because there's a massive existing user base using 1.x on 1.20.1; I don't want them auto-updating to 2.x and have all their memories wiped since it uses a new format.

For 2.x, you can grab the 1.20.1 version from the GitHub releases, but at that stage it's a 'know what you're doing'.

**Comment by KIRUYXAN** [comment]
But it’s more convenient for me to track updates through modrinth, because modmenu also tracks updates through it, and besides, I have a mod for auto-updating all mods, which also works through modrinth
