### ISSUE TITLE
High contrast mode. How do I get rid of it?

### ISSUE THREAD

**Issue by Toilet-Lord** [JackFred2/ChestTracker#194]
Here's the high contrast mode in question:
![06 - 14 33 07 - Tuesday](https://github.com/user-attachments/assets/d4c82788-20b2-489d-a927-5da4a75707a3)

I tried taking the texture to put in my custom-made resource pack (with a lot of fixes and features I like) to see if it would replace the texture but it doesn't work either.

It first appeared at some point when I updated the mod and other mods about 2 weeks ago. Could maybe another mod SOMEHOW be affecting how the Chest Tracker mod displays? 

I thought it was one of my many resource packs at first but I never installed a resource pack that would do that and I tried placing another resource pack containing the textures of the mod (in the right places) on top but nothing happened.

Help

**Comment by JackFred2** [comment]
They're stored under 'high_contrast' in the resources root and loaded by Fabric API's resource loader. If you want to replace them, you should be able to do it by copying their paths.

https://github.com/JackFred2/ChestTracker/tree/1.21/src%2Fclient%2Fresources%2Fhigh_contrast
