### ISSUE TITLE
Feature: Improved Shulker (Item) + Other Nested Inventory & NBT Support

### ISSUE THREAD

**Issue by d0if** [JackFred2/ChestTracker#195]
Let me know if this is feasible, or has been requested before (I couldn't find any previous request/issue/post). I think it could be a great addition to this mod!

### Current Issues
1. **Items with nested inventories, such as shulker boxes, bundles, and ctrl-picked block inventories cannot be searched through.**
    i. You can sometimes become soft-locked out of a search. Say you forgot where you put your eggs, all of which you have packaged into shulker boxes. When you search in the GUI for "egg," you won't get any results. Even though _Where Is It_ would allow you to find your eggs through a nested search, you cannot perform the search through _Chest Tracker_ because the GUI search yielded no results.
    ii.  Currently, the only way to explore the contents of shulker boxes is using shulkerboxtooltips. There is also no way to see a true 'total' item count if some fraction of your items are inside shulker boxes.

2. **(Unsure whether this is an issue with _Chest Tracker_ or _Where Is It_) Cannot perform a search for an item with exact nbt.**
    i. It is impossible to find a specific shulker item. Returning to above example with eggs: suppose you find your egg-filled shulker in the GUI list (e.g. using shulkerboxtooltips). You use the GUI to perform a search for this shulker, but unfortunately, every single chest containing a shulker box is highlighted - regardless of the contents of the shulker box.
    ii. It is impossible to find an item with exclusive (X but not Y) NBT. Suppose I am searching for a piece of armor. In the GUI, I find a pair of leggings with mending and unbreaking that suit my needs. I perform a search, but the search also returns chests containing leggings with mending, unbreaking, and curse of binding, which are undesirable. 

These issues combine to make shulker box/nested inventory management difficult with this mod.

### Possible Solution
Since this mod is so popular, it might not be reasonable to completely change the functionality overnight. I propose the addition of two new toggle switches, each fixing their corresponding problem listed above:
1. **Toggle to treat nested inventories as if they were placed inventories.**
  i. Items with nested inventories could become translucent in a search to indicate that their contents are counted outside of the nested inventory.
  ii. The functionality for nested searches already exists in _Where Is It_ - would only need to add nested contents to the search window.
2. **Toggle to require exact NBT match when performing a search.**
  i. Leave no possibility of extra NBT data; the search result must be an exact copy of what was previewed. Would also allow for finding specific shulker boxes, bundles, or other nested inventories.

Since there is no remaining space for buttons when the search window is at minimum size, I believe that the two new toggles, as well as the two existing search options could be moved to a "filters" dropdown embedded in the search bar.

### Another Possible Solution
Add an alternative interaction to nested inventories in the GUI search. When used, could move down the tree, displaying nested inventory instead of primary search results. Would be slightly less invasive/intensive, and would fix the issue with softlocking searches.

**Comment by JackFred2** [comment]
Have a plan for both; 1 shouldn't be too much trouble. 2 should also be easy enough as where is it has methods for that.

**Comment by JackFred2** [comment]
1: Chest Tracker 2.5.0 will 'unpack' items by default from within shulker boxes; this includes double nested items such as bundles inside shulkers. The containers will still be shown.

![image](https://github.com/user-attachments/assets/8cad9c7c-d992-4739-a725-edd409b0ca21)

**Comment by JackFred2** [comment]
2. I think is a simple constant change but i'll check for side effects; doing that later
