### ISSUE TITLE
Feature: Adding Multiple IPs to the same key for server that can be accessed with multiple IPs

### ISSUE THREAD

**Issue by titlekungCh** [JackFred2/ChestTracker#198]
Describe the solution you'd like
What would you like to see in the mod?
A way to sync the one of the server's chest database with other one on the list, for example server that use SRV will have a public IP such as <play.example.com> with 25565 as port but can also be accessed with <example.com:50266> too, since 50266 is the port the server are really hosted on but SRV redirect <play.example.com:25565> to <example.com:50266>.
The current situation, everytime some situation cause the user to have to change the ip, the database is always reset.

Describe alternatives you've considered
Add a Text Box in the <Editing Memory Bank> Page. allowing you to sync multiple Bank together as if it's the same world.

**Comment by JackFred2** [comment]
Assuming you're on **2.x**:

This should be already possible using the 'Make Default' button when editing the memory bank/database.

If you click 'Make Default' on the same memory bank for each connection, then that memory bank will be loaded for each.
![image](https://github.com/user-attachments/assets/508a7c32-4e58-44b2-9598-aaf298d5057a)
