### ISSUE TITLE
game crash randomly when closing gui

### ISSUE THREAD

**Issue by sametcetinkaya1447** [JackFred2/ChestTracker#199]
![image](https://github.com/user-attachments/assets/3031d03f-6087-427e-9a6f-5a6a427b3006)
heres the log files that i think related to it i use 1.20.4

**Comment by JackFred2** [comment]
What version of YACL are you running?

**Comment by sametcetinkaya1447** [comment]
v 3.3.2+1.20.4 i will try again with updating it

**Comment by JackFred2** [comment]
Assuming resolved
