### ISSUE TITLE
Conflict with the button of the Inventory Profiles

### ISSUE THREAD

**Issue by law4x** [JackFred2/ChestTracker#2]
look Conflict with the button of the Inventory Profiles. [link](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles)
can increase the left alignment or increase the X Y offset configuration
![001](https://user-images.githubusercontent.com/11098142/88456367-bd5feb00-ceaf-11ea-98e1-072fc439d6bb.png)

**Comment by JackFred2** [comment]
I've added a config option to move the buttons in 0.4.5.
