### ISSUE TITLE
ChestTracker Show the shulker but not the inside , 

### ISSUE THREAD

**Issue by Haiden47** [JackFred2/ChestTracker#207]
I tried to load all my chest , because it's a huge mess , and sadly the mod only the shulker , how i can mix it everything with the usual content of the chest , i'm gonna have a ton of chest and shulker , so i look to see if i can have like : X amount of Stone if i include all the shulkers everywhere , and like 200 not empty shulker box , to kinda prevent the problem of how many differents items i'm gonna have

![Capture-4554](https://github.com/user-attachments/assets/7c5a6dca-2217-498d-b90b-e98c24a3da5a)

**Comment by JackFred2** [comment]
Added in 2.5.0; shulkers (and other stuff like bundles) will unpack contained items.
![image](https://github.com/user-attachments/assets/414cc2e0-d482-4383-b529-251b0a7227c2)
