### ISSUE TITLE
Random blocks getting a container name tag because of server commands

### ISSUE THREAD

**Issue by zephyrweather** [JackFred2/ChestTracker#212]
I play on a server that has plugin commands to open menus for things like ender chests and warps, but sometimes when I use the commands to open these menus, a container name tag will appear on any non-container block I'm looking at. Jade will also show the "contents" of the non-container block when I hover over it. The only solution I've found to get the name tags to disappear is to break and replace the block. 

![2024-08-22_15 42 36](https://github.com/user-attachments/assets/9b38fc50-6a6d-4821-a246-b95f6e2c26c5)

The items that are in the command menus will also show up in the search tab if a random block gets the name tag, and will highlight the random block. This also leads to duplicates of items in the command menus to show up in the search tab depending on how many random blocks have been given container name tags.

![2024-08-22_16 02 03](https://github.com/user-attachments/assets/fab7d3d7-6078-481e-8cc0-e7cb73e1af0a) 
![2024-08-22_16 04 15](https://github.com/user-attachments/assets/2e3247ca-d842-44c0-a10f-081aacc9a52e)

Apologies if this is an issue that already has a solution that I just don't understand, I'm not very smart about mod stuff but I'm trying to learn lol
(also sorry the post is so long)

**Comment by JackFred2** [comment]
Should be an easy fix, can just tell the mod to ignore inventories when a command is ran. Will get that out soon along with the other recent issues

Issue length is fine.

**Comment by JackFred2** [comment]
Fixed in upcoming 2.5.0
