### ISSUE TITLE
Display enderchest preview with the same arrangement as it actually is

### ISSUE THREAD

**Issue by MineTheCube** [JackFred2/ChestTracker#216]
Hi!

First of all, thanks for the mod, it is very helpful!!!

I love the enderchest preview on multiplayer server integration with shulker box previews, I just have one small request: to display it exactly as it is.

I have config shulker box preivew to always display full contents, i'd love the same with the enderchest.

What I have now:
![image](https://github.com/user-attachments/assets/25e73174-04b2-42a3-9a92-70659e2f8569)

What I would like to see:
![image](https://github.com/user-attachments/assets/8bf15fb5-adce-4dd6-870a-9df74e5b9c7b)

Thanks!

**Comment by JackFred2** [comment]
Added in upcoming 2.5.0
![image](https://github.com/user-attachments/assets/6f0fb6e6-3427-413a-a2dd-d46d2078a4ca)

**Comment by MineTheCube** [comment]
That's very nice of you! Thanks!!
