### ISSUE TITLE
Crash when clicking on item in the ChestTracker GUI

### ISSUE THREAD

**Issue by SuperSpaceRob** [JackFred2/ChestTracker#22]
**To Reproduce**
I was in Creative mode on a server and clicked the icon to open the ChestTracker GUI, which worked. But then when I clicked on an item (I think it had some special formatting, which might have had something to do with it), I got the screen that said that NotEnoughCrashes had prevented the game from crashing.

**Crash Report**
[crash-2021-04-18_21.43.07-client.txt](https://github.com/JackFred2/ChestTracker/files/6336136/crash-2021-04-18_21.43.07-client.txt)

**Additional context**
I was on the server called DiamondFire and was in code-mode on a plot. If you are not familiar with the server, you basically code stuff by putting stuff in chests. The chests 'move' to the right if you add something in the middle of a line of codeblocks, so ChestTracker might think that there is something in a chest at a location, while there is not a chest there anymore (because it has been moved). At least, that's my theory.
It might have to do with some other mod I am using, NotEnoughCrashes said that LibGUI might have also been the problem. I don't know what LibGUI is though.
After looking at the log, I think that it is a problem with DiamondFire's chest moving. I don't know if that means it is impossible to fix the crash, but here's the log in case you want that as well.😃
[latest.log](https://github.com/JackFred2/ChestTracker/files/6336275/latest.log)

**Comment by JackFred2** [comment]
I'll have a further look in a few hours, but from the looks of it you're on an older version (you've got 0.7.9, whereas the latest is 0.8.13); any chance you can update and see if it changes anything?

**Comment by SuperSpaceRob** [comment]
> I'll have a further look in a few hours, but from the looks of it you're on an older version (you've got 0.7.9, whereas the latest is 0.8.13); any chance you can update and see if it changes anything?

Sorry that I didn't have latest version. I've now changed the version to the newest, and it certainly has changed, but not in a good way. Now when I try to start up minecraft it says that it failed to start and that Where Is It has been found to be the issue...

[crash-2021-04-22_10.58.19-server.txt](https://github.com/JackFred2/ChestTracker/files/6356944/crash-2021-04-22_10.58.19-server.txt)

**Comment by JackFred2** [comment]
Managed to reproduce it, you should be able to fix that issue by placing an updated [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config) into your mods folder.

I think the root cause may be another mod including an old version of cloth config, and that one taking priority over this mod's bundled version; I may stop bundling it on my end so this issue does not crop up in the future.

I appreciate the further debugging by the way, thank you.
