### ISSUE TITLE
Searchables not embedded

### ISSUE THREAD

**Issue by ghost** [JackFred2/ChestTracker#228]
The changelog says that Searchables are embedded, but it is not embedded in Chest Tracker v2.5.0 for 1.21.1 and above.

It's not a major issue, but I'm reporting it just the same.

Thanks.

**Comment by JackFred2** [comment]
It's definitely embedded and loading for me in v2.5.3+1.21.1, Minecraft 1.21.1
![image](https://github.com/user-attachments/assets/3f33f15c-e630-4b30-91fb-a69ad163d1bd)
You aren't running Minecraft 1.21 (not 1.21.1) by any chance? Searchables has strict version matching which might cause it not to enable on that version

**Comment by ghost** [comment]
Ah, yes. I am using 1.21.

 Sorry to have bothered you.
