### ISSUE TITLE
Search items in chests using Litematica material list

### ISSUE THREAD

**Issue by eloix2** [JackFred2/ChestTracker#235]
Greetings! Not sure if this would be possible or if it is interesting enough, but it would be nice to have some kind of button to search all items from an active material list from Litematica mod. I've been building some farms using schematics and I think this would be pretty useful, as I find myself writing every item every time I need something. 

Anyway, amazing mod, it has saved me from going insane!

**Comment by JackFred2** [comment]
It's currently in the 'planned at some point' phase; there used to be a litematica fork that added support themselves, but given I've never really used the mod I'd have to look into it

**Comment by JackFred2** [comment]
Made an experimental implementation that adds two buttons; one to search for all missing and to search for individual missing. Not polished or well tested yet.
![image](https://github.com/user-attachments/assets/ee6f9fdf-11e8-45f7-814a-097b72cb1abd)

It's available on the actions run for now: https://github.com/JackFred2/ChestTracker/actions/runs/11006444663/artifacts/1969536469 (don't use the `-sources` jar.

**Comment by eloix2** [comment]
Hello! Thank you for the quick implementation. I've been testing the actions version, and so far, it seems to be working perfectly! There's just one thing I noticed: it would be nice to have the ability to adjust the duration for which the chests are highlighted when searching for items. When using the "search all missing" option, there's often not enough time to check all the chests. I'm not sure if this feature is already implemented, but I couldn't find any configuration option related to time in the mod settings.

I've attached some screenshots to verify that the implementation is working fine:
![2024-09-24_15 07 15](https://github.com/user-attachments/assets/fe730861-e89e-4da9-9555-35baa7493838)
![2024-09-24_15 08 20](https://github.com/user-attachments/assets/e34f42d7-0f67-4753-9e3a-c3a933ecc334)

(The chest that is not highlighted only contains obsidian, and all the obsidian in the schematic has already been placed, so everything is working as expected.)

**Comment by JackFred2** [comment]
That should be an option under Where Is It's config to extend the time.

**Comment by eloix2** [comment]
You're absolutely right, then everything is fine.

**Comment by JackFred2** [comment]
Finalized in #236
