### ISSUE TITLE
forget this world

### ISSUE THREAD

**Issue by steakfrosch322** [JackFred2/ChestTracker#25]
In my world i clicked on the forget this world button to see what it does and this wasn't a good idea...
Is there any way you can undo that? I alrady tried reinstalling the mod and deleted the modfolder in the .minecraft path.
I hope that anyone can help me.

**Comment by JackFred2** [comment]
Unfortunately, once you've pressed and held the forget world button all item locations are forgotten and can not be undone; you'll need to "re-learn" them again.

**Comment by steakfrosch322** [comment]
how ist this does this work? Beacause as i installed the mod and went into my world all items were already found by the mod is this possible that the mod does this again?

**Comment by JackFred2** [comment]
The mod remembers what items you've seen and where, so if you've started opening chests again it will remember where those items were and start filling the list. Other than that, I'm not sure, maybe the file stayed afterwards for whatever reason.

**Comment by steakfrosch322** [comment]
Okay thanks for your answer i try that.
