### ISSUE TITLE
Add server side where is it compat

### ISSUE THREAD

**Issue by UrBoiTom** [JackFred2/ChestTracker#257]
I'm in a server that has where is it on the server, and that works perfectly, but chest tracker, using its GUI, doesn't as it uses cached client-side info instead of the server side info.

**Comment by JackFred2** [comment]
Not looking for this in the current 2.x version of Chest Tracker; it would require a lot of internal architecture changes to get this working. Possibly in a 3.x where CT can be put on the server.
