### ISSUE TITLE
Feature request - Selectivly ignore containers, spesifically hoppers and droppers

### ISSUE THREAD

**Issue by KvaGram** [JackFred2/ChestTracker#258]
**Is your feature request related to a problem? Please describe.**
I make heavy use of this when setting up my automatic storage system.
The frustration comes when this mod stores info on items in hoppers and droppers in my storage system. Those items won't stay there for long, so the mod showing items in such containers is more of a hindrance than feature.

**Describe the solution you'd like**
A new option in either the mod's settings or search menu, where some storage types can be selectively ignored.

**Describe alternatives you've considered**
Other than knowingly ignoring locations that I know is a hopper or a dropper, nothing can be done.

**Additional context**
Let me know if this feature request should rather be in the whereisit repo, and I'll copy it over there.

**Comment by JackFred2** [comment]
Under filtering settings; there's an option to add only 'common containers' (chests, shulker boxes, barrels) - is that specific enough?

**Comment by KvaGram** [comment]
It might be? I found no such setting when I looked.

**Comment by KvaGram** [comment]
Ah. I found it. I expected to find this in the mod settings. I did not realize the mod had its own menu in the UI to set this.
