### ISSUE TITLE
1.17 Crashes on startup

### ISSUE THREAD

**Issue by Nincodedo** [JackFred2/ChestTracker#26]
**To Reproduce**
I started the game, but the game crashed back to the launcher before the Mojang logo could even come up.

**Crash Report**
[crash-2021-06-11_22.10.52-client.txt](https://github.com/JackFred2/ChestTracker/files/6641578/crash-2021-06-11_22.10.52-client.txt)

**Comment by JackFred2** [comment]
I've stopped bundling [Cloth API](https://www.curseforge.com/minecraft/mc-mods/cloth-api) to avoid some version conflicts, you'll need to install this yourself alongside the mod. I did apparently forget to mark this on curseforge, apologies.

**Comment by Nincodedo** [comment]
That fixed it. Thank you!
