### ISSUE TITLE
Jade Compat

### ISSUE THREAD

**Issue by GuardedHoney53** [JackFred2/ChestTracker#260]
My game is crashing due to an issue with jade
[2024-12-15-3.log.gz](https://github.com/user-attachments/files/18139384/2024-12-15-3.log.gz)

**Comment by JackFred2** [comment]
I can't reproduce this (Chest Tracker 2.6.4+1.21.1; Minecraft 1.21.1; Jade 15.9.1). You seem to have solved this judging by the posts in Fabricord's support channel? Seems to be something else messing up Jade registration, not Chest Tracker or Jade.
