### ISSUE TITLE
Forget specific chests

### ISSUE THREAD

**Issue by breadbyte** [JackFred2/ChestTracker#27]
**Why?**
I'd like to be able to forget or ignore specific chests entirely.
For example, I go to a friend's base and open one of their chests, ChestTracker immediately tracks the chest but I do not want to track this chest (since it is not mine).
My ChestTracker is now tracking items that are not mine.

**Describe the solution you'd like**
An extra button on the chest interface with a tooltip that says 'Forget this chest' or something similar to that effect.

**Describe alternatives you've considered**
Not opening chests other than mine, and forgetting the world whenever I happen to do so.
This is an extremely time consuming task, and a great hassle for someone like me that has a lot of chests for various purposes.

**Comment by JackFred2** [comment]
Added a toggle for remembering new chests, and also a button to forget individual chests, shown by holding shift. Will be out next release.
![image](https://user-images.githubusercontent.com/8350692/122623983-c8a2a300-d08d-11eb-9970-83b67310d3bf.png)
![image](https://user-images.githubusercontent.com/8350692/122623989-d22c0b00-d08d-11eb-9794-ea9e59fbc4d2.png)
