### ISSUE TITLE
Mod forgets chests that are emptied

### ISSUE THREAD

**Issue by LexiTehGallade** [JackFred2/ChestTracker#29]
**Describe the bug**
ChestTracker forgets a chest that is emptied, even if that chest was set to be remembered when using manual mode

**To Reproduce**
In a vanilla server using only Chest Tracker on the client:
Place a double chest, using manual mode shift click to remember the container. The chest will not be remembered.
OR
Place a double chest with any item inside, using manual mode shift click to remember the container. The chest will be remembered. Take the item out, and the chest is forgotten.

**Expected Result**
Manually added containers should never be automatically forgotten.

**Additional context**
This is likely an oversight of the new manual remember system, if I had to guess the intention was that chests like hidden treasure should be forgotten when emptied if added automatically by the mod because they are not permanent player chests and most player chests are not emptied completely.

This could likely be fixed while retaining the "forget random chests" behaviour by adding a special flag when a container is manually added as opposed to the default automatic mode.

**Comment by JackFred2** [comment]
The mod normally doesn't remember empty chests to save file sizes, it doesn't account for manually remembered right now. I'll have a look, but as a work around for now you can give the chest a name in the anvil and it won't be forgotten.

**Comment by JackFred2** [comment]
Fixed, alongside a new button which shows what you have tracked.
