### ISSUE TITLE
Logspams "1" to the game's log

### ISSUE THREAD

**Issue by CompaqDisc** [JackFred2/ChestTracker#30]
**Describe the bug**
When playing the game, your game logs will be spammed with the string "1".
(It appears to be a rogue `System.out.println()`, as there is no timestamp or anything else, just "1")

**To Reproduce**
Load up a multiplayer game, and watch as your game logs have the string "1" continually output to them.
(I opened a chest and clicked the ChestTracker icon before noticing, although even after exiting the inventory the spam continued until a few seconds after I opened the pause menu)

**Expected Result**
I should not be logspammed

**Additional context**
Mod version 1.0.4, downloaded from Modrinth

**Comment by JackFred2** [comment]
I can't reproduce this (1.0.4 from modrinth, connect to a 1.17.1 vanilla server, no logspam). I've also looked through all the code of both ChestTracker and Where Is It and can't find anything obvious that would seem to cause this. Could you post the full latest.log?

**Comment by CompaqDisc** [comment]
Odd, re-enabling the mod doesn't seem to produce this again for me. I can't replicate it on a fresh setup either. Looking through the logs doesn't seem to show any evidence. Perhaps this is some artifact of my launcher? (MultiMC) Anyways, sorry for opening this issue without investigating further first. I suppose I'll close this issue then!
