### ISSUE TITLE
Crash when searching 

### ISSUE THREAD

**Issue by shouxd** [JackFred2/ChestTracker#31]
**To Reproduce**
I just tried to search stuff as usual from inventory.

**Crash Report**
https://paste.gg/p/anonymous/2ea5103b104141408a54eb473d544760

**Additional context**
When I delete chest memories it doesn't crash anymore. But re-opening the game and trying to search again will result in the same crash, again.

**Comment by JackFred2** [comment]
Fixed in 1.0.6
