### ISSUE TITLE
Translate.

### ISSUE THREAD

**Issue by kyrtion** [JackFred2/ChestTracker#32]
You can check POEditor for translate on Russian? Im checked you file ru_ru.json, this file not changed...
If you jave ask, please ask me to telegram @kyrtion , ok?
Thanks you.

Misha.

**Comment by JackFred2** [comment]
Thanks for the translations, I'll get them published in a few minutes. I don't get notified by POEditor when a language is updated or completed, so apologies that I didn't see sooner.

**Comment by kyrtion** [comment]
New bug.
Open gui chesttracker, print random, click CTRL + A for select all text in search again print random. Oh, pront old text not deleted... Check in text document for test.

Idea. (Fast search)
If you opened gui, automatic clicked search for print, for example...
G - gui chesttracker.

[G] and im not clicked search,
Im now print: "Stone" - search understand and now printing in search.

**Comment by kyrtion** [comment]
Set tag suggestions, bug

**Comment by JackFred2** [comment]
Thanks for the translations again, they've been pushed in 1.0.8.
Regarding the GUI updates: I've put them on the TODO list; they shouldn't be too difficult.
