### ISSUE TITLE
Bumb mods in 1.16.5

### ISSUE THREAD

**Issue by kyrtion** [JackFred2/ChestTracker#33]
**Describe the solution you'd like**
_Chest Tracker_ and _Where Is It_

**Describe alternatives you've considered**
No need. I'm need mods update Minecraft versions.

**Additional context**
Nope.

**Comment by JackFred2** [comment]
I'm only focusing on 1.17.x for the mods right now; given the way the mod is structured the differences would probably be too much to maintain both versions. Apologies.

**Comment by kyrtion** [comment]
oh, okey, thank you for answer.
this sugg. are not active.
