### ISSUE TITLE
Issue with GUI's and the hotkey.

### ISSUE THREAD

**Issue by MHFDoge** [JackFred2/ChestTracker#35]
**Describe the bug**
Item menu ignores currently open GUI's when the hotkey is used.
**To Reproduce**
Have virtually any other GUI open, an anvil for example. Try to type something into the anvil that uses whatever key the "open chesttracker GUI" button is bound to. The current GUI will forcibly close, and the chesttracker GUI will be opened.

**Expected Result**
The mod should ignore hotkey usage while the user has a GUI open.

**Additional context**
N/A

**Comment by JackFred2** [comment]
Fixed in a657b7fda02c21d9965410f76e0998c7832da927
