### ISSUE TITLE
1.18 Fabric Misaligned icon

### ISSUE THREAD

**Issue by red2blue** [JackFred2/ChestTracker#38]
Icon offset is way to off.

latest version of chest tracker on 1.18 fabric

![image](https://user-images.githubusercontent.com/35115304/144966451-4d5ee26e-2e5d-4241-a4a0-90f415c9f635.png)

**Comment by JackFred2** [comment]
Fixed; this was due to a workaround for a [bug](https://bugs.mojang.com/browse/MC-193348) which is fixed in 1.18.

**Comment by red2blue** [comment]
appreciate it
