### ISSUE TITLE
Feature Request: Config Option to hide/adjust chest labels

### ISSUE THREAD

**Issue by Voidlighter** [JackFred2/ChestTracker#44]
I absolutely love this mod, though when I have a bunch of stacked named chests, the nametag-styled labels get really distracting and don't look very nice; especially because the names appear inside the chest above them, making it confusing where each label applies.

It would be awesome to have a config option to hide these floating names, and would be additionally awesome to be able to adjust their position to appear in front of the chests or inside them instead of above them.

**Comment by JackFred2** [comment]
The labels should now shift into the chests if the block above is solid (such as another chest above); if you want to disable the labels entirely then you can now set "Name Render Range" to 0 in the config.
