### ISSUE TITLE
Add a button to disable the chest label

### ISSUE THREAD

**Issue by SpacEagle17** [JackFred2/ChestTracker#47]
I would like to see a toggle for labels (the text that appears above chests when they are renamed), so that the player can turn them off.

**Comment by JackFred2** [comment]
Set "Name Render Range" to 0 in the ChestTracker config.

**Comment by siggi147** [comment]
you can not set "Name Render Range" to 0 only 4 and even changing it in the config file and restarting the game just sets it to 4 again. before and after staring the game
