### ISSUE TITLE
All Items of the Same Type Get Highlighted When Searching for a Specific Named Item

### ISSUE THREAD

**Issue by itsloley** [JackFred2/ChestTracker#51]
**Describe the bug**
when you search for named items (for example, dirt blocks named 1, 2, 3, 4, 5, etc...) it will highlight all items under the same type, instead of the named item you want specifically

**To Reproduce**
place multiple items of the same type into multiple separate chests, each one having a unique name & try to find a specific one using the chest tracker

**Expected Result**
it should only highlight the chest with the item having the name that you picked, instead of highlighting every single chest with that same item type

**Additional context**

https://user-images.githubusercontent.com/56316903/155885113-326f0820-a1e0-4e2b-ae5d-025f10a23400.mp4

**Comment by JackFred2** [comment]
You should be able to search with NBT (including the name) by holding shift down when clicking the item.

**Comment by itsloley** [comment]
oh..! i had no idea! that's exactly what i needed.. tysm! :>
