### ISSUE TITLE
Cyrillic names become question marks after relog

### ISSUE THREAD

**Issue by PixelQiwi** [JackFred2/ChestTracker#57]
**Describe the bug**
After reconnecting to a server/reopening the world mod loads cyrillic names of inventories as question marks.

**To Reproduce**
1. Open any world
2. Rename a chest/shulkerbox using cyrillic characters
3. Open the chest to store it
4. Reopen the world
5. The name will become question marks

**Expected Result**
The names should be as they were when opening said inventories (the names show up fine before reconnecting)

**Additional context**
I've noticed that the databases are stored in ANSI encoding, which might be just one several reasons of this issue (ANSI is infamous for breaking cyrillic among many other character sets), using UTF-8 instead would be great as a preventive measure.

I don't think latest.log will be of any use here, but will provide if you _really really_ need it.

Here's a video of me replicating the bug:
https://files.catbox.moe/4ja1w0.mp4

**Comment by JackFred2** [comment]
Specified files to be UTF-8 on read and write; it's possible that some data corruption will occur for existing files  as old encoding gets read as UTF-8. Reopening inventories with corrupted names/item names should fix this and it should be a 1-off issue.
