### ISSUE TITLE
crash when open config menu

### ISSUE THREAD

**Issue by Valtrytocode** [JackFred2/ChestTracker#72]
**To Reproduce**
In 1.19 with sodium and fabric

**Crash Report**
crash when I open the config menu 

**Additional context**
[crash-2022-11-07_22.19.52-client.txt](https://github.com/JackFred2/ChestTracker/files/9955573/crash-2022-11-07_22.19.52-client.txt)

plz help me I realy need to use this mod without crashing

**Comment by JackFred2** [comment]
Looks like you're using a snapshot version of cloth config, which needed breaking changes - [make sure you're using a version for 1.19.x](https://modrinth.com/mod/cloth-config/version/8.2.88%2Bfabric).
