### ISSUE TITLE
Dark mode 

### ISSUE THREAD

**Issue by kittenvr** [JackFred2/ChestTracker#78]
**Describe the solution you'd like**
Makes the GUI dark

**Describe alternatives you've considered**

**Additional context**
I don't want to get flash banged when I open the GUI

**Comment by JackFred2** [comment]
I think there's a setting in LibGui for dark mode GUIs; you may need to enable "Show Libraries" in modmenu to see it.

**Comment by kittenvr** [comment]
> I think there's a setting in LibGui for dark mode GUIs; you may need to enable "Show Libraries" in modmenu to see it.

It kind of works, but the "inventory" is still white
![image](https://user-images.githubusercontent.com/103120356/219747948-2a094899-bc3c-4ded-afc0-56e42a4fd325.png)
