### ISSUE TITLE
Game crashes when hovering the heart button or clicking the searching button

### ISSUE THREAD

**Issue by MrAn0nym** [JackFred2/ChestTracker#8]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2020-09-14 15:45:11 CEST
Description: Rendering screen

java.lang.NoClassDefFoundError: net/minecraft/class_5223$class_5224
    at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.47)
    at spinnery.client.render.BaseRenderer.<clinit>(BaseRenderer.java:21)
    at spinnery.widget.WPanel.draw(WPanel.java:37)
    at spinnery.widget.WInterface.draw(WInterface.java:223)
    at spinnery.client.screen.BaseScreen.render(BaseScreen.java:28)
    at red.jackf.chesttracker.gui.ItemManagerScreen.render(ItemManagerScreen.java:178)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:616)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1023)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
    at net.minecraft.client.MinecraftClient.handler$zca000$afterCrashHandled(MinecraftClient:4844)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zca000$afterCrashHandled(MinecraftClient:4844)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zca000$afterCrashHandled(MinecraftClient:4844)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5223$class_5224
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 30 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Screen render details --
  Screen name: red.jackf.chesttracker.gui.ItemManagerScreen
  Mouse location: Scaled: (540, 153). Absolute: (1080.000000, 306.000000)
  Screen size: Scaled: (924, 508). Absolute: (1848, 1015). Scale factor of 2.000000

-- Affected level --
  All players: 1 total; [class_746['namenlosxy'/153454, l='ClientLevel', x=-383.86, y=63.00, z=272.94]]
  Chunk stats: Client Chunk Cache: 529, 289
  Level dimension: minecraft:overworld
  Level spawn location: World: (64,66,64), Chunk: (at 0,4,0 in 4,4; contains blocks 64,0,64 to 79,255,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 31012738 game time, 13933552 day time
  Server brand: Spigot
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.16.2
  Minecraft Version ID: 1.16.2
  Operating System: Linux (amd64) version 5.4.0-47-generic
  Java Version: 1.8.0_265, Private Build
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
  Memory: 552289512 bytes (526 MB) / 1675100160 bytes (1597 MB) up to 1908932608 bytes (1820 MB)
  CPUs: 8
  JVM Flags: 2 total; -Xms512m -Xmx2048m
  Suspected Mods: Spinnery (spinnery), Fabric Loader (fabricloader), Chest Tracker (chesttracker)
  Fabric Mods: autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
               blue_endless_jankson: jankson 1.2.0
               canvas: Canvas Renderer 1.0.927
               cherishedworlds: Cherished Worlds 1.1.0-1.16.2
               chesttracker: Chest Tracker 0.6.3
               cleardespawn: Clear Despawn 1.16.2-fabric0.17.2-1.1.1
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.0.6
               cloth-config2: Cloth Config v4 4.7.0-unstable
               controlling: Controlling For Fabric 1.1.2
               cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
               dynamicfps: Dynamic FPS 1.2.1
               fabric: Fabric API 0.20.1+build.401-1.16
               fabric-api-base: Fabric API Base 0.1.3+12a8474c4e
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
               fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
               fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1884e
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.7.0+432ea1884e
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea1884e
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e4e
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.5+fcdfdfa14e
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.0+8bcfced84e
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.0+8bcfced84e
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.11+fb0d9b0e4e
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.0+432ea1884e
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf4e
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
               fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e4e
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
               fabricloader: Fabric Loader 0.9.2+build.206
               fermion: Fermion 2.5.202
               fermion-orientation: Fermion Orientation 1.1.201
               fermion-varia: Fermion Varia 2.3.202
               flighthelper: FlightHelper 1.16.2-fabric0.17.2-1.2.1
               frex: FREX 3.3.137
               gbfabrictools: GBfabrictools 1.2.2+1.16.2
               itemscroller: Item Scroller 0.15.0-dev.20200824.205318
               jankson: Jankson 3.0.1+j1.2.0
               joml-mod: JOML Mod 1.4.20
               json-model-extensions: JSON Model Extensions 1.15.124
               kirin: Kirin UI 1.7-1.16.2
               litematica: Litematica 0.0.0-dev.20200824.031346
               loadcatcher: Entrypoint Catcher 2.0.0
               malilib: MaLiLib 0.10.0-dev.21+arne.1
               minecraft: Minecraft 1.16.2
               minihud: MiniHUD 0.19.0-dev.20200829.031650
               modmenu: Mod Menu 1.14.6+build.31
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               now-playing: Now Playing 1.1.4
               org_apache_httpcomponents_httpclient: httpclient 4.5.10
               org_apache_httpcomponents_httpcore: httpcore 4.4.12
               org_apache_httpcomponents_httpmime: httpmime 4.5.10
               org_yaml_snakeyaml: snakeyaml 1.26
               presencefootsteps: Presence Footsteps r28+1.16.2
               skinswapper: Minecraft Skin Change Mod 2.0.1
               special-circumstances: Special Circumstances 1.7.202
               spinnery: Spinnery 3.0.56
               tweakeroo: Tweakeroo 0.10.0-dev.20200829.030647
               viafabric: ViaFabric 0.2.10-SNAPSHOT+build-446.1-mc-1.16
               viaversion: ViaVersion 3.1.0
               voxelmap: VoxelMap 1.10.10
  Launched Version: MultiMC5
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GT 710/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.100, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fancy
  Resource Packs: vanilla, fabric/fabric-renderer-api-v1, fabric/fabric-keybindings-v0, fabric/fabricloader, fabric/fabric-containers-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-game-rule-api-v1, fabric/fabric-api-base, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-textures-v0, fabric/fabric-rendering-fluids-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-lifecycle-events-v1, fabric/fabric-renderer-registries-v1, fabric/fabric-loot-tables-v1, fabric/fabric, fabric/fabric-networking-v0, fabric/fabric-networking-blockentity-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-tool-attribute-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-events-interaction-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-item-api-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-key-binding-api-v1, fabric/fabric-resource-loader-v0, fabric/fabric-content-registries-v0, fabric/fabric-tag-extensions-v0, fabric/fabric-registry-sync-v0, fabric/fabric-mining-levels-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-models-v0, fabric/fabric-item-groups-v0, fabric/fabric-object-builders-v0, fabric/canvas, fabric/cleardespawn, fabric/cloth-config2, fabric/fermion, fabric/fermion-orientation, fabric/fermion-varia, fabric/flighthelper (incompatible), fabric/frex, fabric/gbfabrictools, fabric/itemscroller (incompatible), fabric/jankson, fabric/joml-mod, fabric/json-model-extensions, fabric/litematica (incompatible), fabric/malilib (incompatible), fabric/minihud (incompatible), fabric/modmenu, fabric/special-circumstances, fabric/tweakeroo (incompatible), fabric/voxelmap (incompatible), file/More Canvas, fabric/dynamicfps, fabric/notenoughcrashes, fabric/viafabric, fabric/viaversion
  Current Language: English (US)
  CPU: 8x AMD Ryzen 5 2400G with Radeon Vega Graphics
  Client Crashes Since Restart: 4
  Integrated Server Crashes Since Restart: 0

**Comment by JackFred2** [comment]
The mod does not currently support 1.16.2/3 due to a discontinued library, it's currently being rewritten with a new one. Apologies!
