### ISSUE TITLE
Forge version

### ISSUE THREAD

**Issue by maksunity** [JackFred2/ChestTracker#81]
Hello, should we expect a version of this mod for the Forge client?

**Comment by JackFred2** [comment]
Hi, I have no plans to port this mod to Forge for now.

**Comment by maksunity** [comment]
It's very sad.

**Comment by maksunity** [comment]
I think it would popularize the mod even more

**Comment by denny4-user** [comment]
I fully support this idea. Needs to be ported to Forge 1.19.2+
