### ISSUE TITLE
Resources failed to reload + crash when opening settings

### ISSUE THREAD

**Issue by tajemniktv** [JackFred2/ChestTracker#83]
**To Reproduce**
1. Start the game 
2. Go into settings

**Crash Report**
Crash report: https://mclo.gs/EVfMgpF
Full logs: https://mclo.gs/Y7X3QUL

**Additional context**
Game crashes when going into settings. Also the resources failed to reload right in the menu. Resourcepacks disable themselves

**Comment by JackFred2** [comment]
Struggling to reproduce for now; something appears to be blocking libgui's `shaders/core/tiled_rectangle.json` from loading. I'll have another look later.

**Comment by tajemniktv** [comment]
As expected, disabling owo lib caused game to start normally.

**Comment by JackFred2** [comment]
Nice debugging, seems to be the same as `https://github.com/wisp-forest/owo-lib/issues/117`. Unfortunately, this isn't something I can fix on my end; you'll have to wait for an update on owo lib's end. Alternatively, you can wait for the next Satin release as mentioned in `https://github.com/wisp-forest/owo-lib/issues/120`, which has a fix built-in and disables owo's functionality.
