### ISSUE TITLE
Can't enter world or server with Optifabric installed 1.19.4

### ISSUE THREAD

**Issue by Royalforce1** [JackFred2/ChestTracker#84]
Install Optifabric and Optifine for 1.19.4, as well as the chest tracker mod, the fabric api, and the cloth config, and then attempt to enter a singleplayer world or server. The game should load, save the world your going into, and then crash.

[crash-2023-04-06_14.46.30-client.txt](https://github.com/JackFred2/ChestTracker/files/11174025/crash-2023-04-06_14.46.30-client.txt)

Works fine without Optifabric installed.

**Comment by JackFred2** [comment]
Pretty sure this is the same as #83, just with optifine/optifabric trying to fix the ID as well as Fabric API. Not sure how much I can do at the moment, other than wait for an update.

**Comment by Royalforce1** [comment]
Ight, sounds good. I know mod compatibility can be wonky sometimes.
