### ISSUE TITLE
Pick Block Search

### ISSUE THREAD

**Issue by 0x000006** [JackFred2/ChestTracker#88]
**Describe the solution you'd like**
When you pick block a block and that block is not present in your inventory it should perform a search.

**Describe alternatives you've considered**
A new hotkey for quickly searching for the item in your main hand.

**Additional context**
none

**Comment by JackFred2** [comment]
added ability to search using the hotkey with an item in hand in JackFred2/WhereIsIt@7ac8e27d3d78e5b30d7686c7c0dcd5ff97c22643; it's opt in. not currently in chesttracker but will be in future
