### ISSUE TITLE
Mod Name Display Errors in Mod Menu

### ISSUE THREAD

**Issue by JackHaozhu** [JackFred2/ChestTracker#91]
**Describe the bug**
Mod name stills shows _Where is It_ in Mod Mene

**To Reproduce**
Add _Mod Menu_ and _ChestTracker_ and check this mod in mod menu

**Expected Result**
Mod name should be ChestTracker

**Comment by JackFred2** [comment]
intended behavior; chesttracker is technically an addon for whereisit. will be changed in 2.0
