### ISSUE TITLE
Please update to Minecraft version 1.20 for your mod.

### ISSUE THREAD

**Issue by surfishs** [JackFred2/ChestTracker#93]
Please update to Minecraft version 1.20 for your mod.

**Comment by glxy14colourse** [comment]
I would love to see this mod on 1.20

**Comment by Goldsucher07** [comment]
same here used it in every modpack

**Comment by cnlimiter** [comment]
> same here used it in every modpack



> I would love to see this mod on 1.20

see #94

**Comment by im-PJs** [comment]
Instructions for 1.20.1:
https://github.com/JackFred2/ChestTracker/pull/94#issuecomment-1614139776
