### ISSUE TITLE
Where is it 1.20 dropped, updating should be possible now! 

### ISSUE THREAD

**Issue by VenomousReaperGoat** [JackFred2/ChestTracker#95]
Finally, its time.

**Comment by im-PJs** [comment]
Instructions for 1.20.1:
https://github.com/JackFred2/ChestTracker/pull/94#issuecomment-1614139776

**Comment by Patchuu** [comment]
Venomous check also @JackFred2 response: 
https://github.com/JackFred2/ChestTracker/pull/94#issuecomment-1616704999
He is working on it and soon he will release it.

**Comment by DamnUi** [comment]
any instructions for 1.20 yet?

**Comment by JackFred2** [comment]
updated to 1.20 using #94 ; will be last big update til the rewrite is done
