### ISSUE TITLE
Add API for wthit to allow you to look at memorized items in overlays

### ISSUE THREAD

**Issue by Smotree** [JackFred2/ChestTracker#98]

**Comment by JackFred2** [comment]
Sounds good enough, will probably make more sense for me to use WTHIT's API instead of the other way around. Will look into it for rewrite

**Comment by Smotree** [comment]
Yes I got a bit confused, either you can implement your own "memorized blocks" overlay, would be very handy.

**Comment by JackFred2** [comment]
added for rewrite
![image](https://github.com/JackFred2/ChestTracker/assets/8350692/68645a9d-faeb-44b8-b572-5e8305855cc4)
